# Generated by Django 4.1.13 on 2024-07-08 23:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("fullname", models.CharField(blank=True, max_length=30)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(blank=True, max_length=16)),
                ("phone", models.CharField(blank=True, max_length=16)),
                ("addresses", models.JSONField()),
                (
                    "starch",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        default="low",
                        max_length=7,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=20)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
