# Generated by Django 4.1.13 on 2024-07-09 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_user_options_user_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="isadmin",
            field=models.BooleanField(default=False),
        ),
    ]
