# Generated by Django 4.1.13 on 2024-07-09 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_user_isadmin"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="id",
            new_name="user_id",
        ),
    ]
