# Generated by Django 4.1.13 on 2024-07-09 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_rename_id_user_user_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="user_id",
            new_name="id",
        ),
    ]
