# Generated by Django 4.1.13 on 2024-07-09 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_rename_user_id_user_id"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="User",
            new_name="Users",
        ),
    ]
