# Generated by Django 4.1.13 on 2024-07-09 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_rename_user_users"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="users",
            name="starch",
        ),
        migrations.AddField(
            model_name="users",
            name="last_login",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="users",
            name="addresses",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="users",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="users",
            name="last_modified",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="users",
            name="password",
            field=models.CharField(max_length=128, verbose_name="password"),
        ),
    ]
