# Generated by Django 5.0.7 on 2024-07-09 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_user_delete_users"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="isadmin",
            new_name="is_admin",
        ),
    ]
