# Generated by Django 5.0.7 on 2024-07-09 22:26

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_rename_isadmin_user_is_admin"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="addresses",
        ),
        migrations.CreateModel(
            name="UserAddresses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=255)),
                ("primary", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.user"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "UserAddresses",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                ("created_at", models.DateTimeField(auto_created=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("placed", "Placed"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("delivered", "Delivered"),
                        ],
                        default="placed",
                        max_length=10,
                    ),
                ),
                (
                    "estimated_delivery",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2024, 7, 10, 3, 26, 55, 908525, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                ("cart", models.JSONField()),
                ("schedule", models.JSONField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user",
                        to="app.user",
                    ),
                ),
                (
                    "address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.useraddresses",
                    ),
                ),
            ],
        ),
    ]
