# Generated by Django 5.0.7 on 2024-07-15 13:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_remove_user_addresses_useraddresses_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="estimated_delivery",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 7, 15, 18, 46, 45, 747119, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
